/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BodyMetric = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'bodyFat' : IDL.Float64,
  'date' : IDL.Int,
  'measurements' : IDL.Record({
    'arms' : IDL.Float64,
    'hips' : IDL.Float64,
    'chest' : IDL.Float64,
    'legs' : IDL.Float64,
    'waist' : IDL.Float64,
  }),
});
export const FoodEntry = IDL.Record({
  'carbs' : IDL.Float64,
  'fats' : IDL.Float64,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'protein' : IDL.Float64,
});
export const NutritionLog = IDL.Record({
  'id' : IDL.Nat,
  'waterIntake' : IDL.Float64,
  'date' : IDL.Int,
  'foodEntries' : IDL.Vec(FoodEntry),
});
export const ScheduledWorkout = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Int,
  'workoutId' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'rpe' : IDL.Float64,
  'weight' : IDL.Float64,
  'volumeLoad' : IDL.Float64,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
});
export const Workout = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'date' : IDL.Int,
  'difficulty' : IDL.Float64,
  'exercises' : IDL.Vec(Exercise),
  'feedback' : IDL.Text,
});
export const CoachConfig = IDL.Record({
  'excludedExercises' : IDL.Vec(IDL.Text),
  'preferredWorkoutDuration' : IDL.Nat,
  'restDayFlexibility' : IDL.Float64,
  'overloadAggressiveness' : IDL.Float64,
});
export const FitnessLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const Goal = IDL.Variant({
  'gainMuscle' : IDL.Null,
  'improveEndurance' : IDL.Null,
  'increaseStrength' : IDL.Null,
  'loseWeight' : IDL.Null,
});
export const Profile = IDL.Record({
  'age' : IDL.Nat,
  'weight' : IDL.Float64,
  'height' : IDL.Float64,
  'fitnessLevel' : FitnessLevel,
  'name' : IDL.Text,
  'goals' : IDL.Vec(Goal),
});

export const idlService = IDL.Service({
  'createBodyMetric' : IDL.Func([BodyMetric], [IDL.Nat], []),
  'createNutritionLog' : IDL.Func([NutritionLog], [IDL.Nat], []),
  'createScheduledWorkout' : IDL.Func([ScheduledWorkout], [IDL.Nat], []),
  'createWorkout' : IDL.Func([Workout], [IDL.Nat], []),
  'deleteBodyMetric' : IDL.Func([IDL.Nat], [], []),
  'deleteNutritionLog' : IDL.Func([IDL.Nat], [], []),
  'deleteScheduledWorkout' : IDL.Func([IDL.Nat], [], []),
  'deleteWorkout' : IDL.Func([IDL.Nat], [], []),
  'exportAllData' : IDL.Func(
      [],
      [
        IDL.Record({
          'scheduledWorkouts' : IDL.Vec(ScheduledWorkout),
          'workouts' : IDL.Vec(Workout),
          'bodyMetrics' : IDL.Vec(BodyMetric),
          'coachConfig' : IDL.Opt(CoachConfig),
          'nutritionLogs' : IDL.Vec(NutritionLog),
          'profile' : IDL.Opt(Profile),
        }),
      ],
      ['query'],
    ),
  'getAllBodyMetrics' : IDL.Func([], [IDL.Vec(BodyMetric)], ['query']),
  'getAllNutritionLogs' : IDL.Func([], [IDL.Vec(NutritionLog)], ['query']),
  'getAllScheduledWorkouts' : IDL.Func(
      [],
      [IDL.Vec(ScheduledWorkout)],
      ['query'],
    ),
  'getAllWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'getBodyMetric' : IDL.Func([IDL.Nat], [BodyMetric], ['query']),
  'getCoachConfig' : IDL.Func([], [IDL.Opt(CoachConfig)], ['query']),
  'getNutritionLog' : IDL.Func([IDL.Nat], [NutritionLog], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getScheduledWorkout' : IDL.Func([IDL.Nat], [ScheduledWorkout], ['query']),
  'getWorkout' : IDL.Func([IDL.Nat], [Workout], ['query']),
  'setCoachConfig' : IDL.Func([CoachConfig], [], []),
  'setProfile' : IDL.Func([Profile], [], []),
  'updateBodyMetric' : IDL.Func([IDL.Nat, BodyMetric], [], []),
  'updateNutritionLog' : IDL.Func([IDL.Nat, NutritionLog], [], []),
  'updateScheduledWorkout' : IDL.Func([IDL.Nat, ScheduledWorkout], [], []),
  'updateWorkout' : IDL.Func([IDL.Nat, Workout], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BodyMetric = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'bodyFat' : IDL.Float64,
    'date' : IDL.Int,
    'measurements' : IDL.Record({
      'arms' : IDL.Float64,
      'hips' : IDL.Float64,
      'chest' : IDL.Float64,
      'legs' : IDL.Float64,
      'waist' : IDL.Float64,
    }),
  });
  const FoodEntry = IDL.Record({
    'carbs' : IDL.Float64,
    'fats' : IDL.Float64,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'protein' : IDL.Float64,
  });
  const NutritionLog = IDL.Record({
    'id' : IDL.Nat,
    'waterIntake' : IDL.Float64,
    'date' : IDL.Int,
    'foodEntries' : IDL.Vec(FoodEntry),
  });
  const ScheduledWorkout = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Int,
    'workoutId' : IDL.Nat,
  });
  const Exercise = IDL.Record({
    'rpe' : IDL.Float64,
    'weight' : IDL.Float64,
    'volumeLoad' : IDL.Float64,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
  });
  const Workout = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'date' : IDL.Int,
    'difficulty' : IDL.Float64,
    'exercises' : IDL.Vec(Exercise),
    'feedback' : IDL.Text,
  });
  const CoachConfig = IDL.Record({
    'excludedExercises' : IDL.Vec(IDL.Text),
    'preferredWorkoutDuration' : IDL.Nat,
    'restDayFlexibility' : IDL.Float64,
    'overloadAggressiveness' : IDL.Float64,
  });
  const FitnessLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const Goal = IDL.Variant({
    'gainMuscle' : IDL.Null,
    'improveEndurance' : IDL.Null,
    'increaseStrength' : IDL.Null,
    'loseWeight' : IDL.Null,
  });
  const Profile = IDL.Record({
    'age' : IDL.Nat,
    'weight' : IDL.Float64,
    'height' : IDL.Float64,
    'fitnessLevel' : FitnessLevel,
    'name' : IDL.Text,
    'goals' : IDL.Vec(Goal),
  });
  
  return IDL.Service({
    'createBodyMetric' : IDL.Func([BodyMetric], [IDL.Nat], []),
    'createNutritionLog' : IDL.Func([NutritionLog], [IDL.Nat], []),
    'createScheduledWorkout' : IDL.Func([ScheduledWorkout], [IDL.Nat], []),
    'createWorkout' : IDL.Func([Workout], [IDL.Nat], []),
    'deleteBodyMetric' : IDL.Func([IDL.Nat], [], []),
    'deleteNutritionLog' : IDL.Func([IDL.Nat], [], []),
    'deleteScheduledWorkout' : IDL.Func([IDL.Nat], [], []),
    'deleteWorkout' : IDL.Func([IDL.Nat], [], []),
    'exportAllData' : IDL.Func(
        [],
        [
          IDL.Record({
            'scheduledWorkouts' : IDL.Vec(ScheduledWorkout),
            'workouts' : IDL.Vec(Workout),
            'bodyMetrics' : IDL.Vec(BodyMetric),
            'coachConfig' : IDL.Opt(CoachConfig),
            'nutritionLogs' : IDL.Vec(NutritionLog),
            'profile' : IDL.Opt(Profile),
          }),
        ],
        ['query'],
      ),
    'getAllBodyMetrics' : IDL.Func([], [IDL.Vec(BodyMetric)], ['query']),
    'getAllNutritionLogs' : IDL.Func([], [IDL.Vec(NutritionLog)], ['query']),
    'getAllScheduledWorkouts' : IDL.Func(
        [],
        [IDL.Vec(ScheduledWorkout)],
        ['query'],
      ),
    'getAllWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'getBodyMetric' : IDL.Func([IDL.Nat], [BodyMetric], ['query']),
    'getCoachConfig' : IDL.Func([], [IDL.Opt(CoachConfig)], ['query']),
    'getNutritionLog' : IDL.Func([IDL.Nat], [NutritionLog], ['query']),
    'getProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getScheduledWorkout' : IDL.Func([IDL.Nat], [ScheduledWorkout], ['query']),
    'getWorkout' : IDL.Func([IDL.Nat], [Workout], ['query']),
    'setCoachConfig' : IDL.Func([CoachConfig], [], []),
    'setProfile' : IDL.Func([Profile], [], []),
    'updateBodyMetric' : IDL.Func([IDL.Nat, BodyMetric], [], []),
    'updateNutritionLog' : IDL.Func([IDL.Nat, NutritionLog], [], []),
    'updateScheduledWorkout' : IDL.Func([IDL.Nat, ScheduledWorkout], [], []),
    'updateWorkout' : IDL.Func([IDL.Nat, Workout], [], []),
  });
};

export const init = ({ IDL }) => { return []; };