/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyMetric {
  'id' : bigint,
  'weight' : number,
  'bodyFat' : number,
  'date' : bigint,
  'measurements' : {
    'arms' : number,
    'hips' : number,
    'chest' : number,
    'legs' : number,
    'waist' : number,
  },
}
export interface CoachConfig {
  'excludedExercises' : Array<string>,
  'preferredWorkoutDuration' : bigint,
  'restDayFlexibility' : number,
  'overloadAggressiveness' : number,
}
export interface Exercise {
  'rpe' : number,
  'weight' : number,
  'volumeLoad' : number,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
}
export type FitnessLevel = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface FoodEntry {
  'carbs' : number,
  'fats' : number,
  'calories' : bigint,
  'name' : string,
  'protein' : number,
}
export type Goal = { 'gainMuscle' : null } |
  { 'improveEndurance' : null } |
  { 'increaseStrength' : null } |
  { 'loseWeight' : null };
export interface NutritionLog {
  'id' : bigint,
  'waterIntake' : number,
  'date' : bigint,
  'foodEntries' : Array<FoodEntry>,
}
export interface Profile {
  'age' : bigint,
  'weight' : number,
  'height' : number,
  'fitnessLevel' : FitnessLevel,
  'name' : string,
  'goals' : Array<Goal>,
}
export interface ScheduledWorkout {
  'id' : bigint,
  'date' : bigint,
  'workoutId' : bigint,
}
export interface Workout {
  'id' : bigint,
  'duration' : bigint,
  'date' : bigint,
  'difficulty' : number,
  'exercises' : Array<Exercise>,
  'feedback' : string,
}
export interface _SERVICE {
  'createBodyMetric' : ActorMethod<[BodyMetric], bigint>,
  'createNutritionLog' : ActorMethod<[NutritionLog], bigint>,
  'createScheduledWorkout' : ActorMethod<[ScheduledWorkout], bigint>,
  'createWorkout' : ActorMethod<[Workout], bigint>,
  'deleteBodyMetric' : ActorMethod<[bigint], undefined>,
  'deleteNutritionLog' : ActorMethod<[bigint], undefined>,
  'deleteScheduledWorkout' : ActorMethod<[bigint], undefined>,
  'deleteWorkout' : ActorMethod<[bigint], undefined>,
  'exportAllData' : ActorMethod<
    [],
    {
      'scheduledWorkouts' : Array<ScheduledWorkout>,
      'workouts' : Array<Workout>,
      'bodyMetrics' : Array<BodyMetric>,
      'coachConfig' : [] | [CoachConfig],
      'nutritionLogs' : Array<NutritionLog>,
      'profile' : [] | [Profile],
    }
  >,
  'getAllBodyMetrics' : ActorMethod<[], Array<BodyMetric>>,
  'getAllNutritionLogs' : ActorMethod<[], Array<NutritionLog>>,
  'getAllScheduledWorkouts' : ActorMethod<[], Array<ScheduledWorkout>>,
  'getAllWorkouts' : ActorMethod<[], Array<Workout>>,
  'getBodyMetric' : ActorMethod<[bigint], BodyMetric>,
  'getCoachConfig' : ActorMethod<[], [] | [CoachConfig]>,
  'getNutritionLog' : ActorMethod<[bigint], NutritionLog>,
  'getProfile' : ActorMethod<[], [] | [Profile]>,
  'getScheduledWorkout' : ActorMethod<[bigint], ScheduledWorkout>,
  'getWorkout' : ActorMethod<[bigint], Workout>,
  'setCoachConfig' : ActorMethod<[CoachConfig], undefined>,
  'setProfile' : ActorMethod<[Profile], undefined>,
  'updateBodyMetric' : ActorMethod<[bigint, BodyMetric], undefined>,
  'updateNutritionLog' : ActorMethod<[bigint, NutritionLog], undefined>,
  'updateScheduledWorkout' : ActorMethod<[bigint, ScheduledWorkout], undefined>,
  'updateWorkout' : ActorMethod<[bigint, Workout], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];