/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    rpe: number;
    weight: number;
    volumeLoad: number;
    name: string;
    reps: bigint;
    sets: bigint;
}
export interface CoachConfig {
    excludedExercises: Array<string>;
    preferredWorkoutDuration: bigint;
    restDayFlexibility: number;
    overloadAggressiveness: number;
}
export interface NutritionLog {
    id: bigint;
    waterIntake: number;
    date: bigint;
    foodEntries: Array<FoodEntry>;
}
export interface FoodEntry {
    carbs: number;
    fats: number;
    calories: bigint;
    name: string;
    protein: number;
}
export interface BodyMetric {
    id: bigint;
    weight: number;
    bodyFat: number;
    date: bigint;
    measurements: {
        arms: number;
        hips: number;
        chest: number;
        legs: number;
        waist: number;
    };
}
export interface ScheduledWorkout {
    id: bigint;
    date: bigint;
    workoutId: bigint;
}
export interface Profile {
    age: bigint;
    weight: number;
    height: number;
    fitnessLevel: FitnessLevel;
    name: string;
    goals: Array<Goal>;
}
export interface Workout {
    id: bigint;
    duration: bigint;
    date: bigint;
    difficulty: number;
    exercises: Array<Exercise>;
    feedback: string;
}
export enum FitnessLevel {
    intermediate = "intermediate",
    beginner = "beginner",
    advanced = "advanced"
}
export enum Goal {
    gainMuscle = "gainMuscle",
    improveEndurance = "improveEndurance",
    increaseStrength = "increaseStrength",
    loseWeight = "loseWeight"
}
export interface backendInterface {
    createBodyMetric(bodyMetric: BodyMetric): Promise<bigint>;
    createNutritionLog(nutritionLog: NutritionLog): Promise<bigint>;
    createScheduledWorkout(scheduledWorkout: ScheduledWorkout): Promise<bigint>;
    createWorkout(workout: Workout): Promise<bigint>;
    deleteBodyMetric(id: bigint): Promise<void>;
    deleteNutritionLog(id: bigint): Promise<void>;
    deleteScheduledWorkout(id: bigint): Promise<void>;
    deleteWorkout(id: bigint): Promise<void>;
    exportAllData(): Promise<{
        scheduledWorkouts: Array<ScheduledWorkout>;
        workouts: Array<Workout>;
        bodyMetrics: Array<BodyMetric>;
        coachConfig?: CoachConfig;
        nutritionLogs: Array<NutritionLog>;
        profile?: Profile;
    }>;
    getAllBodyMetrics(): Promise<Array<BodyMetric>>;
    getAllNutritionLogs(): Promise<Array<NutritionLog>>;
    getAllScheduledWorkouts(): Promise<Array<ScheduledWorkout>>;
    getAllWorkouts(): Promise<Array<Workout>>;
    getBodyMetric(id: bigint): Promise<BodyMetric>;
    getCoachConfig(): Promise<CoachConfig | null>;
    getNutritionLog(id: bigint): Promise<NutritionLog>;
    getProfile(): Promise<Profile | null>;
    getScheduledWorkout(id: bigint): Promise<ScheduledWorkout>;
    getWorkout(id: bigint): Promise<Workout>;
    setCoachConfig(config: CoachConfig): Promise<void>;
    setProfile(profile: Profile): Promise<void>;
    updateBodyMetric(id: bigint, bodyMetric: BodyMetric): Promise<void>;
    updateNutritionLog(id: bigint, nutritionLog: NutritionLog): Promise<void>;
    updateScheduledWorkout(id: bigint, scheduledWorkout: ScheduledWorkout): Promise<void>;
    updateWorkout(id: bigint, workout: Workout): Promise<void>;
}
import type { BodyMetric as _BodyMetric, CoachConfig as _CoachConfig, FitnessLevel as _FitnessLevel, Goal as _Goal, NutritionLog as _NutritionLog, Profile as _Profile, ScheduledWorkout as _ScheduledWorkout, Workout as _Workout } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBodyMetric(arg0: BodyMetric): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBodyMetric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBodyMetric(arg0);
            return result;
        }
    }
    async createNutritionLog(arg0: NutritionLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createNutritionLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNutritionLog(arg0);
            return result;
        }
    }
    async createScheduledWorkout(arg0: ScheduledWorkout): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createScheduledWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createScheduledWorkout(arg0);
            return result;
        }
    }
    async createWorkout(arg0: Workout): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkout(arg0);
            return result;
        }
    }
    async deleteBodyMetric(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBodyMetric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBodyMetric(arg0);
            return result;
        }
    }
    async deleteNutritionLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNutritionLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNutritionLog(arg0);
            return result;
        }
    }
    async deleteScheduledWorkout(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteScheduledWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteScheduledWorkout(arg0);
            return result;
        }
    }
    async deleteWorkout(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkout(arg0);
            return result;
        }
    }
    async exportAllData(): Promise<{
        scheduledWorkouts: Array<ScheduledWorkout>;
        workouts: Array<Workout>;
        bodyMetrics: Array<BodyMetric>;
        coachConfig?: CoachConfig;
        nutritionLogs: Array<NutritionLog>;
        profile?: Profile;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.exportAllData();
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportAllData();
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBodyMetrics(): Promise<Array<BodyMetric>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBodyMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBodyMetrics();
            return result;
        }
    }
    async getAllNutritionLogs(): Promise<Array<NutritionLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNutritionLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNutritionLogs();
            return result;
        }
    }
    async getAllScheduledWorkouts(): Promise<Array<ScheduledWorkout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllScheduledWorkouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllScheduledWorkouts();
            return result;
        }
    }
    async getAllWorkouts(): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkouts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkouts();
            return result;
        }
    }
    async getBodyMetric(arg0: bigint): Promise<BodyMetric> {
        if (this.processError) {
            try {
                const result = await this.actor.getBodyMetric(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBodyMetric(arg0);
            return result;
        }
    }
    async getCoachConfig(): Promise<CoachConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoachConfig();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoachConfig();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNutritionLog(arg0: bigint): Promise<NutritionLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getNutritionLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNutritionLog(arg0);
            return result;
        }
    }
    async getProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheduledWorkout(arg0: bigint): Promise<ScheduledWorkout> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduledWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduledWorkout(arg0);
            return result;
        }
    }
    async getWorkout(arg0: bigint): Promise<Workout> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkout(arg0);
            return result;
        }
    }
    async setCoachConfig(arg0: CoachConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCoachConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCoachConfig(arg0);
            return result;
        }
    }
    async setProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfile(to_candid_Profile_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfile(to_candid_Profile_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBodyMetric(arg0: bigint, arg1: BodyMetric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBodyMetric(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBodyMetric(arg0, arg1);
            return result;
        }
    }
    async updateNutritionLog(arg0: bigint, arg1: NutritionLog): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNutritionLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNutritionLog(arg0, arg1);
            return result;
        }
    }
    async updateScheduledWorkout(arg0: bigint, arg1: ScheduledWorkout): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateScheduledWorkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateScheduledWorkout(arg0, arg1);
            return result;
        }
    }
    async updateWorkout(arg0: bigint, arg1: Workout): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkout(arg0, arg1);
            return result;
        }
    }
}
function from_candid_FitnessLevel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FitnessLevel): FitnessLevel {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Goal_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Goal): Goal {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoachConfig]): CoachConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduledWorkouts: Array<_ScheduledWorkout>;
    workouts: Array<_Workout>;
    bodyMetrics: Array<_BodyMetric>;
    coachConfig: [] | [_CoachConfig];
    nutritionLogs: Array<_NutritionLog>;
    profile: [] | [_Profile];
}): {
    scheduledWorkouts: Array<ScheduledWorkout>;
    workouts: Array<Workout>;
    bodyMetrics: Array<BodyMetric>;
    coachConfig?: CoachConfig;
    nutritionLogs: Array<NutritionLog>;
    profile?: Profile;
} {
    return {
        scheduledWorkouts: value.scheduledWorkouts,
        workouts: value.workouts,
        bodyMetrics: value.bodyMetrics,
        coachConfig: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.coachConfig)),
        nutritionLogs: value.nutritionLogs,
        profile: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.profile))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: number;
    height: number;
    fitnessLevel: _FitnessLevel;
    name: string;
    goals: Array<_Goal>;
}): {
    age: bigint;
    weight: number;
    height: number;
    fitnessLevel: FitnessLevel;
    name: string;
    goals: Array<Goal>;
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        fitnessLevel: from_candid_FitnessLevel_n6(_uploadFile, _downloadFile, value.fitnessLevel),
        name: value.name,
        goals: from_candid_vec_n8(_uploadFile, _downloadFile, value.goals)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gainMuscle: null;
} | {
    improveEndurance: null;
} | {
    increaseStrength: null;
} | {
    loseWeight: null;
}): Goal {
    return "gainMuscle" in value ? Goal.gainMuscle : "improveEndurance" in value ? Goal.improveEndurance : "increaseStrength" in value ? Goal.increaseStrength : "loseWeight" in value ? Goal.loseWeight : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
}): FitnessLevel {
    return "intermediate" in value ? FitnessLevel.intermediate : "beginner" in value ? FitnessLevel.beginner : "advanced" in value ? FitnessLevel.advanced : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Goal>): Array<Goal> {
    return value.map((x)=>from_candid_Goal_n9(_uploadFile, _downloadFile, x));
}
function to_candid_FitnessLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): _FitnessLevel {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Goal_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): _Goal {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    weight: number;
    height: number;
    fitnessLevel: FitnessLevel;
    name: string;
    goals: Array<Goal>;
}): {
    age: bigint;
    weight: number;
    height: number;
    fitnessLevel: _FitnessLevel;
    name: string;
    goals: Array<_Goal>;
} {
    return {
        age: value.age,
        weight: value.weight,
        height: value.height,
        fitnessLevel: to_candid_FitnessLevel_n13(_uploadFile, _downloadFile, value.fitnessLevel),
        name: value.name,
        goals: to_candid_vec_n15(_uploadFile, _downloadFile, value.goals)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FitnessLevel): {
    intermediate: null;
} | {
    beginner: null;
} | {
    advanced: null;
} {
    return value == FitnessLevel.intermediate ? {
        intermediate: null
    } : value == FitnessLevel.beginner ? {
        beginner: null
    } : value == FitnessLevel.advanced ? {
        advanced: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Goal): {
    gainMuscle: null;
} | {
    improveEndurance: null;
} | {
    increaseStrength: null;
} | {
    loseWeight: null;
} {
    return value == Goal.gainMuscle ? {
        gainMuscle: null
    } : value == Goal.improveEndurance ? {
        improveEndurance: null
    } : value == Goal.increaseStrength ? {
        increaseStrength: null
    } : value == Goal.loseWeight ? {
        loseWeight: null
    } : value;
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Goal>): Array<_Goal> {
    return value.map((x)=>to_candid_Goal_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
